[package]
name = "pixie_os"
version = "0.1.0"
edition = "2018"
authors = ["Wbert Adrian Castro Vera <dobleuber@gmail.com>"]

[dependencies]


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"