[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-pixie_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

# To set the rust toolchain to nightly
# rustup override set nightly